# Generated by Django 6.0.5 on 2026-05-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_entry_entrymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='content',
            field=models.JSONField(),
        ),
    ]
